[data.email]
    perso = "florent.clarret@gmail.com"
    work = "florent.clarret@datadoghq.com"

[data.hostnames.work]
    intel = "COMP-C02G70X8ML87"
    m1 = "COMP-MWCXH06XC7"

[data.key.work]
    primary = "725D3843DBD883ED"

[data.public_key.work]
    m1 = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDASGhq8xI60e+j+rNsAu3c/HIWMuxmEAFPiRW/cu8g2qAQ9kVvDVQTWnL5HjL8dCufHKDO524RfgmQntcpPjKmeAcJY5+9v3Xnb2kgBchgv0ppJ7Ti7clBUqVloLnHPbC8vyfwHRRi72lBDbR74Tgb24iiGxxsbLdGke2+PNMQesAvdbzC3xhXi6Pqg9izg5xpMJhuIhXA06sT024AirrDGE/f+rYwbl75h/NE6z6dMwIjhScIPGGW5VZtokO61UN9zkjyfnt9zi/ibLff3D3HCe9GMDdU9QPaXhQZo3Oa4OkYzOb12BXyLJd8pJUll1galyrZHYiEV4MeLt3L3gwMNFxVPWgADyieejAuxpnYwKxhecHLYSU3b1Lx7rseTBBfkfSiW9PjaOMBEJUw2xZ/VqQkegNFo07Mue4JsBjN5w+K9sS1ag5XztKcqPG1ejexpPwVVtQ7jQHLwK4r18ifkfdwNb/mqZ+XfkIMvwtnrD5CfZ2qPSYsIaurmt4rgZ8iDf20qtEthJNPJ62kw0WlAi8ScI7SSTKosvb9z0yxabHsEGgEbrmnfoWGaf4Z78rWrUTU/O/oLCnVKPHRzViZn57AbZz5B6c5T8pzTMJqFvhO/ma7S00+Q8YTU2664znqJGQ1J3Q2tf7TN7HSYCDenQKOGmgcK9Jnd42xqgENLw== florent.clarret@COMP-MWCXH06XC7"
    intel = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFc7L4rR7YrA0bT9w15CH+ca4LmFvBtKyX9DSB9sqEP0 florent.clarret@datadoghq.com"

[data.public_key.perso]
    latitude = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3b43jraL3iUNXG1UTAfiOzJpK5ELMp6mr96NsQGfBYp7OtjRMB5imQYONjK9EHWrQ/HppHQwNdKu7RZ3qy2mkqnAEe6YGDRKo2B30OCJwPAKVYioPygj0UZ7u20UgIVMkk0WLHXQvOhRC0hUkUZbpo+oFMFNadffXmMEhg9d5OB/yP/ySkMDGCpJY47ia/p8iZCu1bhnS43rPE0DE2RomdOyzFTBpgdTTCmVVwDUbLrP4gHjP93ZncGRilJgR1oXxgEA/o4nDU2ItvuYZxVLoe/JxtZpDtbh7fAuCgCowxih/DOPgK1swfsSZEMsi1imkggHYnEYQ9/+jmOkJeHef florent.clarret@gmail.com"
    helios = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEzNywQNx8WXye82LWSqw6Uy/bZdpr/mqp3E0AiF+bqW florent.clarret@gmail.com"
